<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[53]=array(0,1,1,'ytfSsw==');
$cfg_Cs[55]=array(0,1,1,'ztLSqtfis7U=');
$cfg_Cs[56]=array(0,1,1,'ztLSqrzTw8s=');
$cfg_Cs[57]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[58]=array(0,1,1,'1+7QwtfK0bY=');
$cfg_Cs[59]=array(0,1,1,'yMjDxbO10M0=');
$cfg_Cs[60]=array(59,1,1,'yczO8dPDs7U=');
$cfg_Cs[61]=array(59,1,1,'u+nH7NPDs7U=');
$cfg_Cs[62]=array(59,1,1,'1f64rtPDs7U=');
$cfg_Cs[63]=array(59,1,1,'xvPStdPDs7U=');
$cfg_Cs[64]=array(59,1,1,'wsPTztPDs7U=');
$cfg_Cs[65]=array(59,1,1,'tPq83dPDs7U=');
$cfg_Cs[66]=array(0,1,1,'yczO8dPDs7U=');
?>