<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQT021.jpg ",93,260);
$z[1][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQT021.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="806";
$z[1][4]['height']="675";
$z[2]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQT021-50.jpg ",262,435);
$z[2][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQT021-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="806";
$z[2][4]['height']="675";

?>