
<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:youxiang itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:gsname itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gsname>

<field:content itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
