<li>
            <a href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]"/></a>
            <div class="list_r">
                <h3>[field:title/]</h3>
                <p>[field:description/]...</p>
                <div class="cl"><a href="[field:arcurl/]" class="more">MORE INFO</a> <span class="list_lm"><img src="../images/08050854_10.gif" alt=""/> [field:typelink/]</span> <span><img src="../images/08050854_15.gif" alt=""/> [field:click/] </span><span><img src="../images/08050854_12.gif" alt=""/> [field:pubdate function="GetDateMK(@me)"/]</span></div>
            </div>
            </li>