<div class="hd">
				<span class="arrow"><a class="next"></a><a class="prev"></a></span>
                               <ul>
                                  <li>商务用车</li>
 <li>婚庆用车</li>
                               </ul>
			</div>
			<div class="bd">
			{dede:arclist titlelen='20' row='6'} 
				<ul>
				
					<li><a href="#@"><img src=[field.picname /] /><br />[field:title /]<span>[field:infos /]</span></a></li>
				</ul>
			 {/dede:arclist}	
				

			</div>