{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/yiyuan/uploads/allimg/150807/1-150PG04538.jpg' text='' width='359' height='209'} /yiyuan/uploads/allimg/150807/1-150PG04538.jpg {/dede:img}
{dede:img ddimg='/yiyuan/uploads/allimg/150807/1-150PG04538-50.jpg' text='' width='379' height='244'} /yiyuan/uploads/allimg/150807/1-150PG04538-50.jpg {/dede:img}
{dede:img ddimg='/yiyuan/uploads/allimg/150807/1-150PG04539.jpg' text='' width='340' height='244'} /yiyuan/uploads/allimg/150807/1-150PG04539.jpg {/dede:img}
{dede:img ddimg='/yiyuan/uploads/allimg/150807/1-150PG04539-50.jpg' text='' width='379' height='244'} /yiyuan/uploads/allimg/150807/1-150PG04539-50.jpg {/dede:img}
