{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQJ504.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQJ504.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQJ504-50.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQJ504-50.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQJ505.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQJ505.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQJ505-50.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQJ505-50.jpg {/dede:img}
