<span class="arrow"><a class="next"></a><a class="prev"></a></span>

                               <ul>
                        
                                  <li>{dede:field name='typename'/}</li>
                             
                               </ul>
			</div>
		
			<div class="bd">
			{dede:arclist titlelen='20' row='6'} 
				<ul>
				
					<li><a href="#@"><img src=""/><br />[field:title /]<span>[field:infos /]</span></a></li>
				</ul>
			 {/dede:arclist}	
				
                         
			</div>