{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQP147.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQP147.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQP148.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQP148.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQP148-50.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQP148-50.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQP148-51.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQP148-51.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQP148-52.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQP148-52.jpg {/dede:img}
