<dl class="tbox">
        <dt><strong><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></strong><span class="more"><a href="{dede:field name='typeurl'/}">¸ü¶à...</a></span></dt>
        <dd>
          <ul class="d1 ico3">
          {dede:arclistsg titlelen='60' row='8'}
            <li><a href="[field:arcurl /]">[field:title /]</a></li>
          {/dede:arclistsg}
          </ul>
        </dd>
    </dl>