<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /yiyuan/uploads/allimg/150807/1-150PG60A2.jpg ",93,248);
$z[1][4]['ddimg']="/yiyuan/uploads/allimg/150807/1-150PG60A2.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="359";
$z[1][4]['height']="209";
$z[2]=Array("img"," /yiyuan/uploads/allimg/150807/1-150PG60A2-50.jpg ",250,411);
$z[2][4]['ddimg']="/yiyuan/uploads/allimg/150807/1-150PG60A2-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="379";
$z[2][4]['height']="244";
$z[3]=Array("img"," /yiyuan/uploads/allimg/150807/1-150PG60A2-51.jpg ",413,574);
$z[3][4]['ddimg']="/yiyuan/uploads/allimg/150807/1-150PG60A2-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="340";
$z[3][4]['height']="244";
$z[4]=Array("img"," /yiyuan/uploads/allimg/150807/1-150PG60A2-52.jpg ",576,737);
$z[4][4]['ddimg']="/yiyuan/uploads/allimg/150807/1-150PG60A2-52.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="379";
$z[4][4]['height']="244";

?>