{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQK425.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQK425.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQK425-50.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQK425-50.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQK426.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQK426.jpg {/dede:img}
{dede:img ddimg='/yiyuandesign/uploads/allimg/150808/1-150PQK426-50.jpg' text='' width='806' height='675'} /yiyuandesign/uploads/allimg/150808/1-150PQK426-50.jpg {/dede:img}
