<div class="hd">
				<!-- 下面是前/后按钮代码，如果不需要删除即可 -->
				<span class="arrow"><a class="next"></a><a class="prev"></a></span>
                           
								<ul>
                                  <li>{dede:field name='typename'/}</li>
                               </ul>
	                    
			</div>
			<div class="bd">
			{dede:arclist titlelen='20' row='6'} 
				<ul>
				
					<li><a href="#@"><img src="{dede:global.cfg_templets_skin/}/images/acd01_35.jpg" /><br />[field:title /]<span>[field:infos /]</span></a></li>
				</ul>
			 {/dede:arclist}	
				

			</div>