<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQP953.jpg ",93,260);
$z[1][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQP953.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="806";
$z[1][4]['height']="675";
$z[2]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQP953-50.jpg ",262,435);
$z[2][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQP953-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="806";
$z[2][4]['height']="675";
$z[3]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQP954.jpg ",437,604);
$z[3][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQP954.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="806";
$z[3][4]['height']="675";
$z[4]=Array("img"," /yiyuandesign/uploads/allimg/150808/1-150PQP954-50.jpg ",606,779);
$z[4][4]['ddimg']="/yiyuandesign/uploads/allimg/150808/1-150PQP954-50.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="806";
$z[4][4]['height']="675";

?>