<ul class="tlist cl">  	
            	{dede:arclist  row='6' titlelen="30"}

                <li>
                    <a href="[field:arcurl/]">
                    <div class="pic"><h3><img src="[field:picname/]" /></h3>
                    <div class="info"><p>[field:title/]</p></div>
                    </div>
                    </a>
                </li>

                {/dede:arclist}
</ul>