<?php
$z[0]=Array("arclist","\r\n\r\n                <li>\r\n                    <a href=\"[field:arcurl/]\">\r\n                    <div class=\"pic\"><h3><img src=\"[field:picname/]\" /></h3>\r\n                    <div class=\"info\"><p>[field:title/]</p></div>\r\n                    </div>\r\n                    </a>\r\n                </li>\r\n\r\n                ",39,405);
$z[0][4]['row']="6";
$z[0][4]['titlelen']="30";

?>