<?php
$z[0]=Array("global","",108,133);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n      	<a href='[field:typeurl/]' >[field:typename/]</a>\r\n      	",155,270);
$z[1][4]['type']="top";
$z[1][4]['row']="4";
$z[2]=Array("global","",341,373);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",416,448);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",575,600);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",866,891);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1626,1658);
$z[6][4]['name']="cfg_templets_skin";

?>