<?php
$z[0]=Array("global","",139,164);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",190,215);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",245,270);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",299,324);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",430,455);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",468,500);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",882,972);
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("global","",982,1007);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("channel","\r\n        <li ><a href=\"[field:typeurl/]\">[field:typename/]<span class=\"size[field:global.autoindex/]\">[field:typenameen/] </span></a></li>\r\n        ",1063,1340);
$z[8][4]['type']="top";
$z[8][4]['row']="6";
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[9]=Array("global","",1473,1505);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1583,1615);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",1701,1733);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",1819,1851);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",1937,1969);
$z[13][4]['name']="cfg_templets_skin";

?>