<?php
$z[0]=Array("global","",48,80);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",332,357);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",418,443);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",510,535);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",599,624);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",684,709);
$z[5][4]['name']="cfg_cmsurl";

?>