<?php
$z[0]=Array("global","",224,249);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",262,294);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",679,769);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",779,804);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li ><a href=\"[field:typeurl/]\">[field:typename/]<span>[field:typenameen/] </span></a></li>\r\n        ",860,1124);
$z[4][4]['type']="top";
$z[4][4]['row']="7";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~<span>~typenameen~</span></a></li>";
$z[5]=Array("global","",1257,1289);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1363,1395);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1481,1513);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1593,1625);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1705,1737);
$z[9][4]['name']="cfg_templets_skin";

?>