<?php
$z[0]=Array("global","",224,249);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",262,294);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",680,770);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",780,805);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li ><a href=\"[field:typeurl/]\">[field:typename/]<span>[field:typenameen/] </span></a></li>\r\n        ",861,1125);
$z[4][4]['type']="top";
$z[4][4]['row']="6";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~<span>~typenameen~</span></a></li>";

?>