<?php
$z[0]=Array("global","",226,258);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",329,363);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("list","\r\n            	<li><a href=\"[field:arcurl/]\"><span>[field:pubdate function=\"GetDateMK(@me)\"/]</span>[field:title/]</a></li>\r\n			  ",1151,1318);
$z[2][4]['pagesize']="15";
$z[3]=Array("pagelist","",1380,1451);
$z[3][4]['listsize']="5";
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[4]=Array("include","",1542,1577);
$z[4][4]['filename']="foot.htm";

?>