<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",367,397);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",434,461);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("global","",789,821);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",888,920);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",989,1021);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1121,1153);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1202,1237);
$z[9][4]['filename']="head.htm";
$z[10]=Array("global","",1297,1329);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",1486,1518);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",1622,1821);
$z[12][4]['type']="son";
$z[12][4]['row']="6";
$z[12][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'>~typename~</a></li>";
$z[13]=Array("list","\r\n			<li>\r\n				<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a>\r\n				<div>\r\n					<h2>[field:title/]</h2>\r\n					<span>[field:infos/]</span>\r\n				</div>\r\n			</li>\r\n            ",1886,2122);
$z[13][4]['pagesize']="20";
$z[13][4]['infolen']="30";
$z[14]=Array("pagelist","",2253,2324);
$z[14][4]['listsize']="5";
$z[14][4]['listitem']="info,index,end,pre,next,pageno";
$z[15]=Array("include","",2379,2416);
$z[15][4]['filename']="footer.htm";

?>