<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",367,397);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",434,461);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("global","",789,821);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",888,920);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",989,1021);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1121,1153);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1193,1228);
$z[9][4]['filename']="head.htm";
$z[10]=Array("global","",1290,1322);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",1437,1469);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",1585,1799);
$z[12][4]['type']="son";
$z[12][4]['row']="6";
$z[12][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='cur'>~typename~</a></li>";
$z[13]=Array("list","\r\n			<li>\r\n				<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a>\r\n				<div class=\"n_biaoti\">\r\n					<h3>[field:title/]</h3>\r\n					<a href=\"[field:arcurl/]\">more</a>\r\n				</div>\r\n			</li>\r\n            ",1870,2130);
$z[13][4]['pagesize']="20";
$z[13][4]['infolen']="30";
$z[14]=Array("include","",2199,2236);
$z[14][4]['filename']="footer.htm";

?>