<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",367,397);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",434,461);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("global","",789,821);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",888,920);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",989,1021);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1121,1153);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1193,1228);
$z[9][4]['filename']="head.htm";
$z[10]=Array("global","",1288,1320);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",1435,1467);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",1581,1797);
$z[12][4]['type']="son";
$z[12][4]['row']="6";
$z[12][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'>~typename~</a></li>";
$z[13]=Array("list","\r\n		<dl>\r\n			<dt>\r\n				<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a>\r\n			</dt>\r\n			<dd>\r\n				<div class=\"n_neirong\">\r\n				    <h3> [field:title/]</h3>\r\n					<p>[field:infos/] </p>\r\n				</div>\r\n				<div class=\"n_chuchu\">\r\n					<span class=\"time\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n				</div>\r\n			</dd>\r\n		</dl>\r\n        ",1838,2250);
$z[13][4]['pagesize']="10";
$z[13][4]['infolen']="30";
$z[14]=Array("pagelist","",2385,2456);
$z[14][4]['listsize']="5";
$z[14][4]['listitem']="info,index,end,pre,next,pageno";
$z[15]=Array("include","",2514,2551);
$z[15][4]['filename']="footer.htm";

?>