<?php
$z[0]=Array("global","",36,68);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",489,521);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",618,834);
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";

?>