<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,534);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",584,616);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",682,714);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",780,812);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",855,887);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("include","",945,980);
$z[10][4]['filename']="head.htm";
$z[11]=Array("channelartlist","\r\n        <a href='{dede:field name='typeurl'/}' class=\"{dede:field.typeid runphp='yes'} if(@me=='31' )@me = 'hover';{/dede:field.typeid}\">{dede:field name='typename'/}</a>\r\n        ",1029,1284);
$z[11][4]['row']="5";
$z[11][4]['typeid']="29,30,31,32,33";
$z[12]=Array("channel","\r\n                        <li class=\"hover[field:global.autoindex/]\"><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n                        ",2387,2586);
$z[12][4]['typeid']="18";
$z[12][4]['row']="6";
$z[13]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">\r\n                            <img src=\"[field:picname/]\" alt=\"[field:title/]\"/><p>[field:title/]</p></a></li>\r\n                            ",2743,3037);
$z[13][4]['typeid']="24";
$z[13][4]['titlelen']="18";
$z[14]=Array("include","",3221,3258);
$z[14][4]['filename']="footer.htm";

?>