<?php
$z[0]=Array("channel","\r\n   <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a> </li>\r\n      ",45,260);
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[0][4]['currentstyle']="<li class='thisclass'><a href='~typelink~'>~typename~</a> </li>";
$z[1]=Array("onetype","[field:typename /]",274,332);
$z[1][4]['typeid']="1";
$z[2]=Array("field","",346,375);
$z[2][4]['name']="position";
$z[3]=Array("list","",390,426);
$z[3][4]['pagesize']="8";
$z[4]=Array("field","",440,471);
$z[4][4]['name']="templeturl";

?>